spring:
  application:
    name: RelationShip
  datasource:
    url: jdbc:postgresql://localhost/relationship_db
    username: postgres
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: true
